---
title: Shooting Stars Are Staircases Too
subtitle: Make Your Mark Scholarship Contest, Spring 2025
format: 
  pdf:
    mainfont: "Vollkorn"
    sansfont: "Petrona"
    linestretch: 1.5
---

<!-- Please create a Video, Literary, Artistic, or Musical Submission in response to the following: Share a person of influence in your life. How has this individual influenced your journey? What impact has their influence had on your life? How does this person inspire you? -->

<!-- This person can be someone from the present or past. They could be a world, cultural, or local hero. Maybe they are an entertainer, athlete, family member, musician, humanitarian, artist, teacher, etc. -->

<!-- Fulfills the request (50%), Creativity (25%), Originality (25%).BONUS POINTS - Letter of Recommendation from faculty or staff member at your school. -->

It was a dark and chilly winter night, with a makeshift bonfire lighting up a stingy diameter on the barren rock of Makalidurga Hill. We huddled around it, on bedsheets not thick enough for the cold bed of the granite monolith, as a bunch of kids somewhere between clueless naivety and newfound conviction in life. The flickering of the flames was mirrored around us by the hearty thoughts of the local nightjars and cicadas of the mysterious scrub jungle. Amongst our shivering bodies, and matching our energy and chuckles impressively for his age, was the person that had shattered our mental paradigms of professorship.

Dr P. U. Antony, to us Antony Sir or just Sir. An incredibly influential mentor who opened up whole new worlds to wide-eyed young kids. Who put us in situations that made us grow both personally and professionally. The times we spent together with Sir were instrumental in helping us expand our worldviews and discover our own paths. 

Antony Sir's flavour of the teacher-student relationship disregarded the conventional power dynamic and hierarchy. Our relationship felt almost oxymoronic, because I could call him "sir" and yet have a deep connection with him. It exemplified how a teacher can also be equal parts friend and mentor, treating the student with the respect they deserve, almost as a peer and foremost as another person. A teacher can match the levels of energy and mischief of the student, whether that is drinking together or making coy jokes or coming up with silly ideas. That night on Makalidurga, he agreed with our wild suggestion that the best way to catch some sleep in that cold was to pack ourselves inside the tiny temple on the hilltop. Time and time again, he reminded us of the importance of seeking adventure and prioritising pure fun in life. 

His boundless energy and fun-loving attitude were not only infectious, but also extremely inspirational and humbling. Hiking up Makalidurga, as with every other hill we had hiked up, he had convinced us to foresake the man-made staircase chiselled into the rock face which would have offered us no challenge. He was also always the first to reach the peak, leaving behind a metaphorical dust cloud of his physical superiority at more than three times our age; we were always left panting in this dust cloud, not quite sure how to feel about it all.

Teaching was indeed Sir's true calling, and he showcased the fundamental virtues of this profession, trying his best to expand the horizons of his students. He encouraged us into the habit of learning by doing, challenging us with tasks such as organising a national seminar, publishing a book, and restoring a wetland, to name a few. We therefore gradually internalised this mindset of stepping outside our comfort zones, seeking out and creating opportunities instead of waiting for them, and striving for multifaceted growth. These traits did not just help my younger college self, but have also stuck with me as fundamental attitudes that guide my journey in life even today. 

With this growth in life and the gradual distillation of my interests, I have had to confront the unfortunate reality of having too many curiosities and too little time. However, I have learned from Antony Sir that although I may not be able to pursue all my interests with equal vigour, I can still use the path I have chosen to make small changes in those peripheral passions. The fact is that my position is truly unique, and these many small changes eventually snowball into significant impacts.

Another lesson that has proved more useful the older I have grown, especially in today's world of polarising discourse, is the ability to respect differences. A staunch believer of God, he often interpreted moments in life very differently to how us students of biology (and evolution) did, leaving us in positions of disagreement and incomprehension. At the same time though, he was also not one to take himself or life too seriously, and we all had the space to joke about our differences of opinion. I learned that seemingly contradictory beliefs often need not be reconciled, that it is indeed possible, and peaceful, to just let them be.

The role of human connections in life cannot be exaggerated. I like to think of every person in the world as climbing their own helical staircase in the multidimensional space of life. Everyone involved in our life has steps in common with us. The majority of staircases only briefly intersect our own, but some have disproportionate impacts on its trajectory and act as critical inflection points. For me, one such inflection, which moved me towards worlds I had never imagined, was unsurprisingly during those college days when I shared numerous steps with Sir. 

Those three undergraduate years were a domino chain, and I came out on the other side with a semblance of direction in life. I had gone into college clueless, having selected my zoology programme simply because I had always liked pets and I thought I would like studying animals. I had not known fields like ecology, evolutionary biology, and wildlife conservation even existed, or that I could make a career in them. I was a shy introvert who had many latent interests. And now, nine years later, I am pursuing a PhD in ecology---it turns out I do indeed like studying animals! Writing is now a passion that I devote considerable time and energy into, and birdwatching has been adopted into my life as something far more significant than a hobby. The framework for my life hinges on these three central axes. I still consider myself introverted, but have learned to switch modes when required. Doing, and stepping out of my comfort zone, are still my biggest learning opportunities and remain a big priority. 

It might be tough to trace back every single step that I shared with Sir, but I am content simply knowing of the overlap and seeing how far I have come from that point. Every single person I laughed with that night inside Makalidurga Temple is now miles and miles away from our shared steps, but I am incredibly grateful to have had such beautiful human connections in my life. The bar is high for the next staircase that might come along, but I cannot wait.
